apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ parameters.name }}-service
  description: {{ parameters.description }}
  tags:
    - nodejs
    - express
spec:
  type: service
  lifecycle: production
  owner: {{ parameters.owner }}

---
apiVersion: backstage.io/v1alpha1
kind: ALMIntegration
metadata:
  name: {{ parameters.name }}-alm
  description: ALM integration for {{ parameters.name }}
spec:
  owner: {{ parameters.owner }}
  integration:
    type: github
    url: '{{ parameters.repoUrl }}'
    repository: '{{ parameters.name }}'
    issueTracker: true
    ci: true
    scm: github
