apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: alm-java-template-sviluppo
  description: Template Java per un repository ALM
  tags:
    - java
    - alm
  annotations:
    backstage.io/managed-by-location: url:https://github.com/paesanv/backstage-test01/blob/main/catalog-info.yaml
    backstage.io/managed-by: https://github.com/paesanv/backstage-test01
spec:
  type: template
  lifecycle: experimental
  owner: ALM Team
  implementsApis:
    - backstage.io/scaffolder-template
---

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: alm-java-repo
  title: Java Repository Template
  description: Crea una struttura base per un'applicazione Java.
  tags:
    - java
    - repository
    - alm
spec:
  owner: ALM
  type: service

  parameters:
    - title: Project Name
      type: string
      required: true
      description: Il nome del progetto

    - title: Repository URL
      type: string
      required: true
      description: URL del repository Git ALM dove verrà creato il progetto

    - title: Package Name
      type: string
      required: true
      description: Il package name per la nuova applicazione Java

    - title: Description # Aggiunta del parametro description per il package.json
      type: string
      required: true
      description: La descrizione del progetto

  steps:
    - id: fetch
      name: Fetch template
      action: fetch:template
      input:
        url: ./template # Percorso locale alla cartella template

    - id: execute
      name: Esegui comando
      action: execute:shellCommand
      input:
        command: mvn clean package # Esegue il packaging Maven per il progetto

    - id: publish
      name: Publish to Git
      action: publish:github
      input:
        repoUrl: '{{ parameters.repoUrl }}'
        description: "Repository Java generated from ALM template"
        repoVisibility: private

    - id: register
      name: Register in Backstage
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: /catalog-info.yaml
